# 01.01 - PROYECTO KAGGLE

In [ ]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()

## download data directly from Kaggle

- create a file `kaggle.json` with your authentication token (in kaggle $\to$ click user icon on top-right $\to$ settings $\to$ API create new token)
- upload it to this notebook workspace
- run the following cell

In [ ]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = '.'
!chmod 600 ./kaggle.json
!kaggle competitions download -c udea-ai4eng-20242

udea-ai4eng-20242.zip: Skipping, found more recently modified local copy (use --force to force download)

## unzip and inspect data

In [ ]:
!unzip udea*.zip > /dev/null

In [ ]:
!wc *.csv

   296787    296787   4716673 submission_example.csv
   296787   4565553  50135751 test.csv
   692501  10666231 118025055 train.csv
  1286075  15528571 172877479 total

## load `train.csv` data with pandas

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("train.csv")
print ("shape of loaded dataframe", df.shape)

shape of loaded dataframe (692500, 12)

In [ ]:
df.head(100)

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,ESTU_PAGOMATRICULAPROPIO,RENDIMIENTO_GLOBAL
0,904256,20212,ENFERMERIA,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Postgrado,No,medio-alto
1,645256,20212,DERECHO,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Técnica o tecnológica incompleta,No,bajo
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Secundaria (Bachillerato) completa,No,bajo
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Secundaria (Bachillerato) completa,No,alto
4,989032,20212,PSICOLOGIA,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Primaria completa,No,medio-bajo
...,...,...,...,...,...,...,...,...,...,...,...,...
95,883625,20195,"LICENCIATURA EN EDUCACIÓN FÍSICA, RECREACIÓN Y...",BOGOTÁ,Entre 1 millón y menos de 2.5 millones,Entre 11 y 20 horas,Estrato 1,Si,Primaria incompleta,Primaria completa,Si,medio-bajo
96,122346,20203,LICENCIATURA EN INGLÉS,SUCRE,Entre 1 millón y menos de 2.5 millones,Más de 30 horas,Estrato 3,Si,Primaria incompleta,Secundaria (Bachillerato) completa,Si,alto
97,360114,20212,DERECHO,VALLE,Entre 2.5 millones y menos de 4 millones,Entre 11 y 20 horas,Estrato 4,Si,Técnica o tecnológica incompleta,Educación profesional completa,Si,bajo
98,539712,20195,LICENCIATURA EN PEDAGOGIA INFANTIL,VALLE,Entre 500 mil y menos de 1 millón,Más de 30 horas,Estrato 4,Si,Técnica o tecnológica incompleta,Educación profesional incompleta,Si,alto
99,208003,20212,LICENCIATURA EN EDUCACION BÁSICA CON ÉNFASIS E...,BOGOTÁ,Entre 1 millón y menos de 2.5 millones,Menos de 10 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Técnica o tecnológica completa,Si,medio-bajo

#### let's check the data types of the columns

In [ ]:
print(df.info())

print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692500 entries, 0 to 692499
Data columns (total 12 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              692500 non-null  int64
 1   PERIODO                         692500 non-null  int64
 2   ESTU_PRGM_ACADEMICO             692500 non-null  object
 3   ESTU_PRGM_DEPARTAMENTO          692500 non-null  object
 4   ESTU_VALORMATRICULAUNIVERSIDAD  686213 non-null  object
 5   ESTU_HORASSEMANATRABAJA         661643 non-null  object
 6   FAMI_ESTRATOVIVIENDA            660363 non-null  object
 7   FAMI_TIENEINTERNET              665871 non-null  object
 8   FAMI_EDUCACIONPADRE             669322 non-null  object
 9   FAMI_EDUCACIONMADRE             668836 non-null  object
 10  ESTU_PAGOMATRICULAPROPIO        686002 non-null  object
 11  RENDIMIENTO_GLOBAL              692500 non-null  object
dtypes: int64(2), object(10)
memory usage: 63.4+ MB
None
                  ID        PERIODO
count  692500.000000  692500.000000
mean   494606.130576   20198.366679
std    285585.209455      10.535037
min         1.000000   20183.000000
25%    247324.750000   20195.000000
50%    494564.500000   20195.000000
75%    741782.500000   20203.000000
max    989286.000000   20213.000000

#### Now, let's check the missing values

In [ ]:
df.isnull().sum()

ID                                    0
PERIODO                               0
ESTU_PRGM_ACADEMICO                   0
ESTU_PRGM_DEPARTAMENTO                0
ESTU_VALORMATRICULAUNIVERSIDAD     6287
ESTU_HORASSEMANATRABAJA           30857
FAMI_ESTRATOVIVIENDA              32137
FAMI_TIENEINTERNET                26629
FAMI_EDUCACIONPADRE               23178
FAMI_EDUCACIONMADRE               23664
ESTU_PAGOMATRICULAPROPIO           6498
RENDIMIENTO_GLOBAL                    0
dtype: int64

#### Let's create a copy of the dataframe

In [ ]:
df_copy = df.copy()

#### Let's fill the missing values of the columns

#### `ESTU_VALORMATRICULAUNIVERSIDAD`

In [ ]:
df_copy.ESTU_VALORMATRICULAUNIVERSIDAD.values[df_copy.ESTU_VALORMATRICULAUNIVERSIDAD.isna()] = 'no info'
df_copy['ESTU_VALORMATRICULAUNIVERSIDAD'].isna().sum()

0

#### `ESTU_HORASSEMANATRABAJA`

In [ ]:
df_copy.ESTU_HORASSEMANATRABAJA.values[df_copy.ESTU_HORASSEMANATRABAJA.isna()] = 'no info'
df_copy['ESTU_HORASSEMANATRABAJA'].isna().sum()

0

#### `FAMI_ESTRATOVIVIENDA`

In [ ]:
df_copy.FAMI_ESTRATOVIVIENDA.values[df_copy.FAMI_ESTRATOVIVIENDA.isna()] = 'no info'
df_copy['FAMI_ESTRATOVIVIENDA'].isna().sum()

0

#### `FAMI_TIENEINTERNET`

In [ ]:
df_copy.FAMI_TIENEINTERNET.values[df_copy.FAMI_TIENEINTERNET.isna()] = 'no info'
df_copy['FAMI_TIENEINTERNET'].isna().sum()

0

#### `FAMI_EDUCACIONPADRE`

In [ ]:
df_copy.FAMI_EDUCACIONPADRE.values[df_copy.FAMI_EDUCACIONPADRE.isna()] = 'no info'
df_copy['FAMI_EDUCACIONPADRE'].isna().sum()

0

#### `FAMI_EDUCACIONMADRE`

In [ ]:
df_copy.FAMI_EDUCACIONMADRE.values[df_copy.FAMI_EDUCACIONMADRE.isna()] = 'no info'
df_copy['FAMI_EDUCACIONMADRE'].isna().sum()

0

In [ ]:
df_copy.ESTU_PAGOMATRICULAPROPIO.values[df_copy.ESTU_PAGOMATRICULAPROPIO.isna()] = 'no info'
df_copy['ESTU_PAGOMATRICULAPROPIO'].isna().sum()

ValueError: invalid literal for int() with base 10: 'no info'

In [ ]:
df_copy.isnull().sum()

ID                                0
PERIODO                           0
ESTU_PRGM_ACADEMICO               0
ESTU_PRGM_DEPARTAMENTO            0
ESTU_VALORMATRICULAUNIVERSIDAD    0
ESTU_HORASSEMANATRABAJA           0
FAMI_ESTRATOVIVIENDA              0
FAMI_TIENEINTERNET                0
FAMI_EDUCACIONPADRE               0
FAMI_EDUCACIONMADRE               0
ESTU_PAGOMATRICULAPROPIO          0
RENDIMIENTO_GLOBAL                0
dtype: int64

In [ ]:
cmap = {'Entre 1 millón y menos de 2.5 millones': 1.75,
 'Entre 2.5 millones y menos de 4 millones': 3.25,
 'Menos de 500 mil': .250,
 'Entre 500 mil y menos de 1 millón': .75,
 'Entre 4 millones y menos de 5.5 millones': 4.75,
 'Más de 7 millones': 7.75,
 'Entre 5.5 millones y menos de 7 millones': 6.25,
 'No pagó matrícula': 0,
 'no info': -1}

df_copy.ESTU_VALORMATRICULAUNIVERSIDAD = np.r_[[cmap[i] for i in df_copy.ESTU_VALORMATRICULAUNIVERSIDAD]]
df_copy.ESTU_VALORMATRICULAUNIVERSIDAD.value_counts()

# df['ESTU_VALORMATRICULAUNIVERSIDAD']

# df_copy['ESTU_VALORMATRICULAUNIVERSIDAD'] = df_copy['ESTU_VALORMATRICULAUNIVERSIDAD'].fillna(df['ESTU_VALORMATRICULAUNIVERSIDAD'].median())

ESTU_VALORMATRICULAUNIVERSIDAD
 1.75    204048
 3.25    127430
 0.25     80263
 0.75     78704
 4.75     69736
 7.75     68014
 6.25     38490
 0.00     19528
-1.00      6287
Name: count, dtype: int64

In [ ]:
# Get the unique values of the column FAMI_ESTRATOVIVIENDA
df_copy["FAMI_ESTRATOVIVIENDA"].unique()
cmap = {'Estrato 3': 3,
    'Estrato 2': 2,
    'Estrato 4': 4,
    'Estrato 1': 1,
    'Estrato 5': 5,
    'Estrato 6': 6,
    'Sin Estrato': -1,
    'no info': -1}

df_copy.FAMI_ESTRATOVIVIENDA = np.r_[[cmap[i] for i in df_copy.FAMI_ESTRATOVIVIENDA]]
df_copy.FAMI_ESTRATOVIVIENDA.value_counts()

FAMI_ESTRATOVIVIENDA
 2    232671
 3    210685
 1    111991
 4     65514
-1     35426
 5     23608
 6     12605
Name: count, dtype: int64

In [ ]:
df_copy["FAMI_EDUCACIONPADRE"].unique()

cmap = {'Primaria completa': 2,
    'Secundaria (Bachillerato) completa': 4,
    'Primaria incompleta': 1,
    'Secundaria (Bachillerato) incompleta': 3,
    'Técnica o tecnológica completa': 6,
    'Educación profesional incompleta': 7,
    'Técnica o tecnológica incompleta': 5,
    'Educación profesional completa': 8,
    'Postgrado': 9,
    'No sabe': -1,
    'No Aplica': -1,
    'no info': -1,
    'Ninguno':0,
}

df_copy.FAMI_EDUCACIONPADRE = np.r_[[cmap[i] for i in df_copy.FAMI_EDUCACIONPADRE]]
df_copy.FAMI_EDUCACIONMADRE = np.r_[[cmap[i] for i in df_copy.FAMI_EDUCACIONMADRE]]
print(df_copy.FAMI_EDUCACIONPADRE.value_counts())
print(df_copy.FAMI_EDUCACIONMADRE.value_counts())

FAMI_EDUCACIONPADRE
 4    128289
 1    125675
 8     83117
 3     71654
 6     62995
 2     55958
-1     48999
 9     44169
 7     27084
 5     22552
 0     22008
Name: count, dtype: int64
FAMI_EDUCACIONMADRE
 4    141744
 1     99420
 6     89542
 8     85326
 3     81012
 2     56125
 9     46246
-1     28599
 5     27533
 7     22470
 0     14483
Name: count, dtype: int64

In [ ]:
df_copy.ESTU_HORASSEMANATRABAJA.value_counts()

cmap = {
    '0': 0,
    'Menos de 10 horas': 5,
    'Entre 11 y 20 horas': 15,
    'Entre 21 y 30 horas': 25,
    'Más de 30 horas': 35,
    'no info': -1,
}

df_copy.ESTU_HORASSEMANATRABAJA = np.r_[[cmap[i] for i in df_copy.ESTU_HORASSEMANATRABAJA]]

#### `ESTU_PRGM_ACADEMICO`

In [ ]:
df_copy

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,ESTU_PAGOMATRICULAPROPIO,RENDIMIENTO_GLOBAL
0,904256,20212,ENFERMERIA,BOGOTÁ,6.25,5,3,Si,5,9,No,medio-alto
1,645256,20212,DERECHO,ATLANTICO,3.25,0,3,No,6,5,No,bajo
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,3.25,35,3,Si,4,4,No,bajo
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,4.75,0,4,Si,-1,4,No,alto
4,989032,20212,PSICOLOGIA,ANTIOQUIA,3.25,25,3,Si,2,2,No,medio-bajo
...,...,...,...,...,...,...,...,...,...,...,...,...
692495,25096,20195,BIOLOGIA,LA GUAJIRA,0.75,15,2,Si,4,3,Si,medio-alto
692496,754213,20212,PSICOLOGIA,NORTE SANTANDER,3.25,35,3,Si,1,3,No,bajo
692497,504185,20183,ADMINISTRACIÓN EN SALUD OCUPACIONAL,BOGOTÁ,1.75,5,3,Si,4,3,Si,medio-bajo
692498,986620,20195,PSICOLOGIA,TOLIMA,3.25,5,1,No,2,2,Si,bajo
692499,933374,20195,PSICOLOGIA,ANTIOQUIA,6.25,35,4,Si,4,6,No,alto

In [ ]:
# Fill nan values with 'no info'
df_copy.ESTU_PAGOMATRICULAPROPIO.values[df_copy.ESTU_PAGOMATRICULAPROPIO.isna()] = 'no info'
df_copy.ESTU_PAGOMATRICULAPROPIO.value_counts()

cmap = {
    'Si': 1,
    'No': 0,
    'no info': -1
}

df_copy.ESTU_PAGOMATRICULAPROPIO = np.r_[[cmap[i] for i in df_copy.ESTU_PAGOMATRICULAPROPIO]]

In [ ]:
df_copy

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,ESTU_PAGOMATRICULAPROPIO,RENDIMIENTO_GLOBAL
0,904256,20212,ENFERMERIA,BOGOTÁ,6.25,5,3,Si,5,9,0,medio-alto
1,645256,20212,DERECHO,ATLANTICO,3.25,0,3,No,6,5,0,bajo
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,3.25,35,3,Si,4,4,0,bajo
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,4.75,0,4,Si,-1,4,0,alto
4,989032,20212,PSICOLOGIA,ANTIOQUIA,3.25,25,3,Si,2,2,0,medio-bajo
...,...,...,...,...,...,...,...,...,...,...,...,...
692495,25096,20195,BIOLOGIA,LA GUAJIRA,0.75,15,2,Si,4,3,1,medio-alto
692496,754213,20212,PSICOLOGIA,NORTE SANTANDER,3.25,35,3,Si,1,3,0,bajo
692497,504185,20183,ADMINISTRACIÓN EN SALUD OCUPACIONAL,BOGOTÁ,1.75,5,3,Si,4,3,1,medio-bajo
692498,986620,20195,PSICOLOGIA,TOLIMA,3.25,5,1,No,2,2,1,bajo
692499,933374,20195,PSICOLOGIA,ANTIOQUIA,6.25,35,4,Si,4,6,0,alto

In [ ]:
df_copy["RENDIMIENTO_GLOBAL"]
cmap = {
    'medio-alto': 3,
    'bajo': 0,
    'alto': 2,
    'medio-bajo': 1
}

df_copy["RENDIMIENTO_GLOBAL"] = np.r_[[cmap[i] for i in df_copy["RENDIMIENTO_GLOBAL"]]]

#### Let's create dummies for the categorical columns

In [ ]:
import pandas as pd
df_dummies_estu_prgm_departamento = pd.get_dummies(df_copy['ESTU_PRGM_DEPARTAMENTO'], dtype=int)
df_dummies_fami_tieneinternet = pd.get_dummies(df_copy['FAMI_TIENEINTERNET'], dtype=int)
df_dummies_fami_estratovivienda = pd.get_dummies(df_copy['FAMI_ESTRATOVIVIENDA'], dtype=int)

X2 = pd.concat([df_dummies_fami_tieneinternet, df_dummies_fami_estratovivienda], axis=1)
X4 = pd.concat([df_dummies_estu_prgm_departamento, df_dummies_fami_estratovivienda], axis=1)

y = df_copy['RENDIMIENTO_GLOBAL']
y

0         3
1         0
2         0
3         2
4         1
         ..
692495    3
692496    0
692497    1
692498    0
692499    2
Name: RENDIMIENTO_GLOBAL, Length: 692500, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.model_selection import train_test_split

X2tr, X2ts, y2tr, y2ts = train_test_split(X2,y, train_size=0.7)
print(X2tr.shape, X2ts.shape, y2tr.shape, y2ts.shape)

X4tr, X4ts, y4tr, y4ts = train_test_split(X4,y, train_size=0.7)
print(X4tr.shape, X4ts.shape, y4tr.shape, y4ts.shape)

(484749, 10) (207751, 10) (484749,) (207751,)
(484749, 38) (207751, 38) (484749,) (207751,)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [ ]:

reg_model = LinearRegression()
# reg_model.fit(X2tr, y2tr)
# y_pred_reg = reg_model.predict(X4ts)

# mse_reg = mean_squared_error(y2ts, y_pred_reg)
# mae_reg = mean_absolute_error(y2ts, y_pred_reg)
# print(f"Regresion Lineal, mse: {mse_reg}, mae: {mae_reg}")

# Si estás usando pandas, convierte las columnas a cadenas
X2tr.columns = X2tr.columns.astype(str)
X2ts.columns = X2ts.columns.astype(str)

# Ajusta el modelo y haz las predicciones
reg_model = LinearRegression()
reg_model.fit(X2tr, y2tr)

y_pred_reg = reg_model.predict(X2ts)

# Calcula los errores MSE y MAE
mse_reg = mean_squared_error(y2ts, y_pred_reg)
mae_reg = mean_absolute_error(y2ts, y_pred_reg)

print(f"Regresion Lineal, mse: {mse_reg}, mae: {mae_reg}")

Regresion Lineal, mse: 1.2000893769745657, mae: 0.9485358117541401

In [ ]:

reg_model = LinearRegression()
# reg_model.fit(X2tr, y2tr)
# y_pred_reg = reg_model.predict(X4ts)

# mse_reg = mean_squared_error(y2ts, y_pred_reg)
# mae_reg = mean_absolute_error(y2ts, y_pred_reg)
# print(f"Regresion Lineal, mse: {mse_reg}, mae: {mae_reg}")

# Si estás usando pandas, convierte las columnas a cadenas
X4tr.columns = X4tr.columns.astype(str)
X4ts.columns = X4ts.columns.astype(str)

# Ajusta el modelo y haz las predicciones
reg_model = LinearRegression()
reg_model.fit(X4tr, y4tr)

y_pred_reg = reg_model.predict(X4ts)

# Calcula los errores MSE y MAE
mse_reg = mean_squared_error(y4ts, y_pred_reg)
mae_reg = mean_absolute_error(y4ts, y_pred_reg)

print(f"Regresion Lineal, mse: {mse_reg}, mae: {mae_reg}")

Regresion Lineal, mse: 1.1929555254199076, mae: 0.9450618337125934